<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="WebForm3.aspx.vb" Inherits="WebApplication1.WebForm3" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server" style="background-color: #008000">
    &nbsp;&nbsp;&nbsp;<br />
    &nbsp;&nbsp;&nbsp;
    <asp:Label ID="Label3" runat="server" Text="student management form" 
        Font-Bold="True" Font-Italic="True" Font-Size="27pt" Height="84px" 
        style="margin-left: 160px" Width="789px"></asp:Label>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
    &nbsp;&nbsp;&nbsp;
    <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Underline="True" 
        Text="Registration form"></asp:Label>
    &nbsp;&nbsp;
    <br />
    <asp:Button ID="Buttonrefersh11" runat="server" 
        style="margin-left: 452px; margin-top: 6px" Text="Refresh" />
    <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button6" runat="server" Text="search" />
    &nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp; &nbsp;
    <br />
&nbsp;&nbsp;&nbsp;
    <br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        BorderColor="Black" BorderStyle="None" DataKeyNames="sno" 
        DataSourceID="SqlDataSource3" ForeColor="Black" Height="270px" 
        Width="971px" DataMember="DefaultView" AutoGenerateEditButton="True" 
        AutoGenerateDeleteButton="True">
        <Columns>
            <asp:BoundField DataField="sno" HeaderText="sno" 
                SortExpression="sno" />
            <asp:BoundField DataField="firstname" HeaderText="firstname" 
                SortExpression="firstname" />
            <asp:BoundField DataField="secondname" HeaderText="secondname" 
                SortExpression="secondname" />
            <asp:BoundField DataField="lastname" HeaderText="lastname" 
                SortExpression="lastname" />
            <asp:BoundField DataField="idno" HeaderText="idno" SortExpression="idno" />
            <asp:BoundField DataField="accno" HeaderText="accno" 
                SortExpression="accno" />
            <asp:BoundField DataField="dob" HeaderText="dob" SortExpression="dob" />
            <asp:BoundField DataField="gender" HeaderText="gender" 
                SortExpression="gender" />
            <asp:BoundField DataField="email" HeaderText="email" 
                SortExpression="email" />
            <asp:BoundField DataField="password" HeaderText="password" 
                SortExpression="password" />
        </Columns>
    </asp:GridView>
  <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
    ConnectionString="<%$ ConnectionStrings:allowancs_dbConnectionString %>" 
    SelectCommand="SELECT [sno], [firstname], [secondname], [lastname], [idno], [accno], [dob], [gender], [email], [username], [password] FROM [regstbl]"
    DeleteCommand="DELETE FROM [regstbl] WHERE [sno] = @sno"
    UpdateCommand="UPDATE [regstbl] SET [firstname] = @firstname, [secondname] = @secondname, [lastname] = @lastname, [idno] = @idno, [accno] = @accno, [dob] = @dob, [gender] = @gender, [email] = @email, [username] = @username, [password] = @password WHERE [sno] = @sno">
    <DeleteParameters>
        <asp:Parameter Name="sno" Type="Int32" />
    </DeleteParameters>
    <UpdateParameters>
        <asp:Parameter Name="firstname" Type="String" />
        <asp:Parameter Name="secondname" Type="String" />
        <asp:Parameter Name="lastname" Type="String" />
        <asp:Parameter Name="idno" Type="String" />
        <asp:Parameter Name="accno" Type="String" />
        <asp:Parameter Name="dob" Type="DateTime" />
        <asp:Parameter Name="gender" Type="String" />
        <asp:Parameter Name="email" Type="String" />
        <asp:Parameter Name="username" Type="String" />
        <asp:Parameter Name="password" Type="String" />
        <asp:Parameter Name="sno" Type="Int32" />
    </UpdateParameters>
</asp:SqlDataSource>




    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button8" runat="server" style="width: 46px" Text="Back" />
    &nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button9" runat="server" Text="next page" Width="67px" />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    </form>
</body>
</html>
